name: futhy
dependencies:
  - base >= 4.7 && < 5
  - containers
  - mtl
  - process
  - futhark
  - filepath
  - transformers
  - optparse-applicative
  - assoc-list
  - flow
  - hmatrix
  - hxt
  - time
  - deepseq
  - matplotlib
  - aeson
  - random
  - bytestring
  - text
  - unordered-containers
  - utf8-string
#  - hstats

ghc-options:
  - -Wall
  - -fforce-recomp
  - -fprof-auto
  - -fprof-cafs
  - -fwarn-unused-imports
  - -fwarn-unused-binds

library:
  source-dirs: src

executables:
  futhy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    #- -rtsopts
    #- -with-rtsopts=-N
    - -with-rtsopts=-A32m
    dependencies:
    - futhy

tests:
  integration-tests:
    main:                Tests.hs
    source-dirs:         test
    ghc-options:
    - -main-is Tests
    dependencies:
    - futhy
    - tasty
    - tasty-hunit
#    - QuickCheck
#    - tasty-quickcheck
#    Consider moving quickcheck to a new category

benchmarks:
  bench:
    main:                Benchmarks.hs
    source-dirs:
    - benchmark
    - test
    ghc-options:
    - -with-rtsopts=-A32m
    - "+RTS --nonmoving-gc -T -RTS"
    - -main-is Benchmarks
    #- -threaded
    dependencies:
    - futhy
    - tasty
    - tasty-bench
    - tasty-hunit
    - deepseq
    - random

