name: futhy
dependencies:
  - base >= 4.7 && < 5
  - containers
  - mtl
  - process
  - futhark
  - filepath
  - transformers
  - optparse-applicative
  - assoc-list
  - flow

ghc-options: -Wall

library:
  source-dirs: src

executables:
  futhy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - futhy

tests:
  integration-tests:
    main:                Tests.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - futhy
    - tasty
    - tasty-hunit
    - QuickCheck
    - tasty-quickcheck
