name: futhy
dependencies:
  - base >= 4.7 && < 5
  - containers
  - mtl
  - process
  - futhark
  - filepath
  - transformers
  - optparse-applicative
  - assoc-list
  - flow
  - hmatrix
  - hxt
  - time
  - tasty-bench

ghc-options: -Wall

library:
  source-dirs: src

executables:
  futhy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - futhy

tests:
  integration-tests:
    main:                Tests.hs
    source-dirs:         test
    dependencies:
    - futhy
    - tasty
    - tasty-hunit
#    - QuickCheck
#    - tasty-quickcheck
#    Consider moving quickcheck to a new category

benchmarks:
  bench:
    main:                Benchmarks.hs
    source-dirs:         benchmark
    #ghc-options:
    #- -main-is           Benchmarks.hs
    #- -threaded
    dependencies:
    - base
    - containers
    - futhy
    - tasty
    - tasty-bench
    - deepseq

